export const GET_PRODUCTS = 'GET_PRODUCTS';
export const LOCATION_LOADING = 'LOCATION_LOADING';
export const ORDER_LOADING = 'ORDER_LOADING';
export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';
export const SET_SEARCHING_MED_LIST = 'SET_SEARCHING_MED_LIST';
export const SET_FOUNDED_SEARCH_MED_LIST = 'SET_FOUNDED_SEARCH_MED_LIST';
export const REMOVE_SEARCHING_MED_LIST = 'REMOVE_SEARCHING_MED_LIST';
export const SET_CLUSTER_SEARCH = 'SET_CLUSTER_SEARCH';
export const SET_MEDICINE_PACKAGES = 'SET_MEDICINE_PACKAGES';
export const CLEAR_MEDICINE_PACKAGES = 'CLEAR_MEDICINE_PACKAGES';


export const GET_LOCATION = 'GET_LOCATION';
export const SET_LOCATION_SUGGESTIONS = 'SET_LOCATION_SUGGESTIONS';
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';
export const SET_MAP_COORDS = 'SET_MAP_COORDS';
export const SET_STORES_CLUSTER = 'SET_STORES_CLUSTER';
export const SET_STORES_CITY = 'SET_STORES_CITY';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REORDERED_CART = 'REORDERED_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SET_PREFERED_ADDRESS = 'SET_PREFERED_ADDRESS';


export const SET_NUMBER = 'SET_NUMBER';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_PERSON = 'SET_PERSON';
export const SET_ORDER_SUCCESS = 'SET_ORDER_SUCCESS';
export const CLEAR_CART = 'CLEAR_CART';
export const SET_SUCCESS_INVOICE = 'SET_SUCCESS_INVOICE';

export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';

export const SET_AUTH = 'SET_AUTH';
export const DE_AUTH = 'DE_AUTH';

